// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: likes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLike = `-- name: CreateLike :one
INSERT INTO likes (id, created_at, updated_at, user_id, post_id) 
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, post_id
`

type CreateLikeParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, createLike,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.PostID,
	)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
	)
	return i, err
}

const deleteLike = `-- name: DeleteLike :one
DELETE FROM likes WHERE post_id = $1
RETURNING id, created_at, updated_at, user_id, post_id
`

func (q *Queries) DeleteLike(ctx context.Context, postID uuid.UUID) (Like, error) {
	row := q.db.QueryRowContext(ctx, deleteLike, postID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
	)
	return i, err
}

const getPostLikes = `-- name: GetPostLikes :one
SELECT post_id, COUNT(*) AS likes_count
FROM likes
WHERE post_id = $1
GROUP BY post_id
`

type GetPostLikesRow struct {
	PostID     uuid.UUID
	LikesCount int64
}

func (q *Queries) GetPostLikes(ctx context.Context, postID uuid.UUID) (GetPostLikesRow, error) {
	row := q.db.QueryRowContext(ctx, getPostLikes, postID)
	var i GetPostLikesRow
	err := row.Scan(&i.PostID, &i.LikesCount)
	return i, err
}

const getUsersFromLikes = `-- name: GetUsersFromLikes :many
SELECT users.username, users.id AS user_like
FROM likes
JOIN users ON likes.user_id = users.id
WHERE likes.post_id = $1
`

type GetUsersFromLikesRow struct {
	Username string
	UserLike uuid.UUID
}

func (q *Queries) GetUsersFromLikes(ctx context.Context, postID uuid.UUID) ([]GetUsersFromLikesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersFromLikes, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersFromLikesRow
	for rows.Next() {
		var i GetUsersFromLikesRow
		if err := rows.Scan(&i.Username, &i.UserLike); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
