openapi: 3.0.0

info:
  title: Twitter clone
  description: |
    API spec for twitter clone app done by Oscar Perez Romero
  version: 1.0.0

tags:
  - name: Users
    description: Users API

  - name: Posts
    description: Posts API

  - name: Follows
    description: Follows API

  - name: Likes
    description: Likes API

paths:
  $ref: ./paths/_index.yaml

components:
  $ref: ./components/_index.yaml
