name: Frontend install
description: 'Install frontend app'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install NPM
      shell: bash
      run: cd frontend && npm ci

    - name: Run lint
      shell: bash
      run: cd frontend && npm run lint
