name: Backend Railway DB
description: 'Deploy Railway database'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Railway
      shell: bash
      run: npm i -g @railway/cli

    - name: Deploy
      shell: bash
      run: railway up --service=${{ secrets.RAILWAY_SERVICE }} -d
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
