name: Frontend e2e tests
description: 'Run frontend e2e tests'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install NPM
      shell: bash
      run: npm ci

    - name: Run lint
      shell: bash
      run: npm run lint

    - name: Install playwright
      shell: bash
      run: npx playwright install --with-deps

    - name: Run e2e tests
      shell: bash
      run: npm run test:e2e
