name: Say hello

on:
  push:
    branches:
      - feat/frontend/add-github-actions

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Oscar!"
