name: Deployment pipeline

on:
  push:
    branches:
      - 'feat/frontend/add-github-actions'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Frontend CI
        uses: ./frontend/.github/workflows/action.yml
