name: Deployment pipeline

on:
  push:
    branches:
      - 'feat/frontend/add-github-actions'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Frontend Workflow
        uses: ./frontend/.github/workflows
