name: Backend Railway DB
runs-on: ubuntu-22.04
steps:
    - uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - uses: actions/setup-node@v4
    with:
      node-version: 18

  - name: Install Railway
    run: npm i -g @railway/cli

  - name: Deploy
    run: railway up --service=${{ secrets.RAILWAY_SERVICE }} -d
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
